#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../../..
PACKAGE_DIR = ircam/jmax/editors/objects/patcher

include $(ROOTDIR)/java/Makefiles/Makefile.common

INCLUDE_PATH := $(JAVA_SRC_ROOT)/$(PACKAGE_DIR)
include Sources2

all:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
.PHONY: all

ErmesObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObject.java)
.PHONY: ErmesObject

ErmesObjBang:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjBang.java)
.PHONY: ErmesObjBang


ErmesObjComment:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjComment.java)
.PHONY: ErmesObjComment


ErmesObjEditable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjEditable.java)
.PHONY: ErmesObjEditable


ErmesObjEditableObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjEditableObject.java)
.PHONY: ErmesObjEditableObject


ErmesObjExternal:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjExternal.java)
.PHONY: ErmesObjExternal


ErmesObjFloat:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjFloat.java)
.PHONY: ErmesObjFloat


ErmesObjIn:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjIn.java)
.PHONY: ErmesObjIn


ErmesObjInOut:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInOut.java)
.PHONY: ErmesObjInOut


ErmesObjInt:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInt.java)
.PHONY: ErmesObjInt


ErmesObjMessage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjMessage.java)
.PHONY: ErmesObjMessage


ErmesObjNumberBox:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjNumberBox.java)
.PHONY: ErmesObjNumberBox


ErmesObjOut:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjOut.java)
.PHONY: ErmesObjOut


ErmesObjPatcher:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjPatcher.java)
.PHONY: ErmesObjPatcher


ErmesObjSlider:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjSlider.java)
.PHONY: ErmesObjSlider


ErmesObjSliderDialog:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjSliderDialog.java)
.PHONY: ErmesObjSliderDialog


ErmesObjToggle:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjToggle.java)
.PHONY: ErmesObjToggle



include $(ROOTDIR)/java/Makefiles/Makefile.misc


