#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  
#


ROOTDIR = ../../../../..
PACKAGE_DIR = ircam/jmax/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
.PHONY: all



MaxFtsConnectCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxFtsConnectCmd.java)
.PHONY: MaxFtsConnectCmd

MaxOpenCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxOpenCmd.java)
.PHONY: MaxOpenCmd

MaxQuitCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxQuitCmd.java)
.PHONY: MaxQuitCmd

MaxRunHooksCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxRunHooksCmd.java)
.PHONY: MaxRunHooksCmd

MaxSystemPropertyCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxSystemPropertyCmd.java)
.PHONY: MaxSystemPropertyCmd

MaxWhenCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxWhenCmd.java)
.PHONY: MaxWhenCmd

MaxSourceCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxSourceCmd.java)
.PHONY: MaxSourceCmd

MaxSysSourceCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxSysSourceCmd.java)
.PHONY: MaxSysSourceCmd

MaxSplashCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxSplashCmd.java)
.PHONY: MaxSplashCmd

MaxGetMaxVersionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxGetMaxVersionCmd.java)
.PHONY: MaxGetMaxVersionCmd

MaxPreloadClassCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxPreloadClassCmd.java)
.PHONY: MaxPreloadClassCmd

MaxOscilloscopeCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) MaxOscilloscopeCmd.java)
.PHONY: MaxOscilloscopeCmd

TclMaxPackage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) TclMaxPackage.java)
.PHONY: TclMaxPackage


include $(ROOTDIR)/java/Makefiles/Makefile.misc




