#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../..
PACKAGE_DIR = ircam/jmax/editors/ermes

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
	(cd tcl; $(MAKE) all)
.PHONY: all

ErmesModule:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesModule.java)
.PHONY: ErmesModule

ErmesConnection:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesConnection.java)
.PHONY: ErmesConnection


ErmesObjBang:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjBang.java)
.PHONY: ErmesObjBang

ErmesObjComment:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjComment.java)
.PHONY: ErmesObjComment

ErmesObjEditField:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjEditField.java)
.PHONY: ErmesObjEditField

ErmesObjEditableObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjEditableObject.java)
.PHONY: ErmesObjEditableObject

ErmesObjExternal:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjExternal.java)
.PHONY: ErmesObjExternal

ErmesObjFloat:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjFloat.java)
.PHONY: ErmesObjFloat

ErmesObjFloatDialog:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjFloatDialog.java)
.PHONY: ErmesObjFloatDialog

ErmesObjIn:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjIn.java)
.PHONY: ErmesObjIn

ErmesObjInOutChoice:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInOutChoice.java)
.PHONY: ErmesObjInOutChoice

ErmesObjInOutPop:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInOutPop.java)
.PHONY: ErmesObjInOutPop

ErmesObjInOutlet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInOutlet.java)
.PHONY: ErmesObjInOutlet

ErmesObjInlet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInlet.java)
.PHONY: ErmesObjInlet

ErmesObjInletOutlet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInletOutlet.java)
.PHONY: ErmesObjInletOutlet

ErmesObjInt:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjInt.java)
.PHONY: ErmesObjInt

ErmesObjMessThread:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjMessThread.java)
.PHONY: ErmesObjMessThread

ErmesObjMessage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjMessage.java)
.PHONY: ErmesObjMessage

ErmesObjOut:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjOut.java)
.PHONY: ErmesObjOut

ErmesObjOutInlet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjOutInlet.java)
.PHONY: ErmesObjOutInlet

ErmesObjOutlet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjOutlet.java)
.PHONY: ErmesObjOutlet

ErmesObjPatcher:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjPatcher.java)
.PHONY: ErmesObjPatcher

ErmesObjSlider:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjSlider.java)
.PHONY: ErmesObjSlider

ErmesObjSliderDialog:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjSliderDialog.java)
.PHONY: ErmesObjSliderDialog

ErmesObjTextArea:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjTextArea.java)
.PHONY: ErmesObjTextArea

ErmesObjThrottle:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjThrottle.java)
.PHONY: ErmesObjThrottle

ErmesObjToggle:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjToggle.java)
.PHONY: ErmesObjToggle

ErmesObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObject.java)
.PHONY: ErmesObject

ErmesPatcherDoc:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesPatcherDoc.java)
.PHONY: ErmesPatcherDoc

ErmesRegion:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesRegion.java)
.PHONY: ErmesRegion

ErmesScrollerView:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesScrollerView.java)
.PHONY: ErmesScrollerView

ErmesSketchHelper:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSketchHelper.java)
.PHONY: ErmesSketchHelper

ErmesSketchPad:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSketchPad.java)
.PHONY: ErmesSketchPad

ErmesSketchWindow:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSketchWindow.java)
.PHONY: ErmesSketchWindow

ErmesToggleButton:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesToggleButton.java)
.PHONY: ErmesToggleButton

ErmesToolBar:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesToolBar.java)
.PHONY: ErmesToolBar

ErmesSwToolbar:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSwToolbar.java)
.PHONY: ErmesSwToolbar

ErmesSwVarEdit:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSwVarEdit.java)
.PHONY: ErmesSwVarEdit

ErmesToolBarLayout:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesToolBarLayout.java)
.PHONY: ErmesToolBarLayout

ErmesSwToggleButton:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSwToggleButton.java)
.PHONY: ErmesSwToggleButton

ErmesKeyAdapter:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesKeyAdapter.java)
.PHONY: ErmesKeyAdapter

ErmesClipboardProvider:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesClipboardProvider.java)
.PHONY: ErmesClipboardProvider

ErmesArea:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesArea.java)
.PHONY: ErmesArea

ErmesDrawable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesDrawable.java)
.PHONY: ErmesDrawable

ErmesSelection:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSelection.java)
.PHONY: ErmesSelection

ErmesPatcherFactory:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesPatcherFactory.java)
.PHONY: ErmesPatcherFactory

include $(ROOTDIR)/java/Makefiles/Makefile.misc
