;; arithmetics (6)
(help-patch "+" (file-cat dir "help" "arith.help.jmax"))
(help-patch "-" (file-cat dir "help" "arith.help.jmax"))
(help-patch "*" (file-cat dir "help" "arith.help.jmax"))
(help-patch "/" (file-cat dir "help" "arith.help.jmax"))
(help-patch "inv*" (file-cat dir "help" "arith.help.jmax"))
(help-patch "inv+" (file-cat dir "help" "arith.help.jmax"))
(help-patch "%" (file-cat dir "help" "arith.help.jmax"))

;; comparison operators (6)
(help-patch "<=" (file-cat dir "help" "compare.help.jmax"))
(help-patch "==" (file-cat dir "help" "compare.help.jmax"))
(help-patch ">" (file-cat dir "help" "compare.help.jmax"))
(help-patch ">=" (file-cat dir "help" "compare.help.jmax"))
(help-patch "!=" (file-cat dir "help" "compare.help.jmax"))
(help-patch "<" (file-cat dir "help" "compare.help.jmax"))

;; logic operators (4)
(help-patch "|" (file-cat dir "help" "logic.help.jmax"))
(help-patch "||" (file-cat dir "help" "logic.help.jmax"))
(help-patch "&&" (file-cat dir "help" "logic.help.jmax"))
(help-patch "&" (file-cat dir "help" "logic.help.jmax"))

;;shifting operators (2)
(help-patch "<<" (file-cat dir "help" "shift.help.jmax"))
(help-patch ">>" (file-cat dir "help" "shift.help.jmax"))

