#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  

all:
	(cd mess; $(MAKE) all)
	(cd utils; $(MAKE) all)
	(cd datalib; $(MAKE) all)
	(cd ftl; $(MAKE) all)
	(cd dsp; $(MAKE) all)
	(cd veclib; $(MAKE) all)
.PHONY: all

clean:
	(cd mess; $(MAKE) clean)
	(cd utils; $(MAKE) clean)
	(cd datalib; $(MAKE) clean)
	(cd ftl; $(MAKE) clean)
	(cd dsp; $(MAKE) clean)
	(cd veclib; $(MAKE) clean)
.PHONY: clean
