
all:
	(cd mess; $(MAKE) all)
	(cd utils; $(MAKE) all)
	(cd datalib; $(MAKE) all)
	(cd ftl; $(MAKE) all)
	(cd dsp; $(MAKE) all)
	(cd veclib; $(MAKE) all)
.PHONY: all

clean:
	(cd mess; $(MAKE) clean)
	(cd utils; $(MAKE) clean)
	(cd datalib; $(MAKE) clean)
	(cd ftl; $(MAKE) clean)
	(cd dsp; $(MAKE) clean)
	(cd veclib; $(MAKE) clean)
.PHONY: clean
