# 
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  Authors: Maurizio De Cecco, Francois Dechelle, Enzo Maggi, Norbert Schnell.
#
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  
# 

all:
	(cd c; $(MAKE) all)
#	(cd java; $(MAKE) all)

all_c:
	(cd c; $(MAKE) all)

all_java:
#	(cd java; $(MAKE) all)

clean:
	(cd c; $(MAKE) clean)
#	(cd java; $(MAKE) clean)

clean_c:
	(cd c; $(MAKE) clean)

clean_java:
#	(cd java; $(MAKE) clean)

.PHONY: all
.PHONY: all_c
.PHONY: all_java

.PHONY: clean
.PHONY: clean_c
.PHONY: clean_java

