;;
;; help patch declarations for the ispw standard signal classes
;;

;; Summary
(help-summary "ISPW signal summary" (file-cat dir "ispw.signal.summary.jmax"))

;; filters (5)
(help-patch "2p2z~" (file-cat dir "2p2z~.help.jmax"))
(help-patch "2pole~" (file-cat dir "2pole~.help.jmax"))
(help-patch "biquad~" (file-cat dir "biquad~.help.jmax"))
(help-patch "wahwah~" (file-cat dir "wahwah~.help.jmax"))
(help-patch "samphold~" (file-cat dir "samphold~.help.jmax"))

;; trigonometrics and logarithms (10)
(help-patch "sin~" (file-cat dir "trigon~.help.jmax"))
(help-patch "cos~" (file-cat dir "trigon~.help.jmax"))
(help-patch "tan~" (file-cat dir "trigon~.help.jmax"))
(help-patch "asin~" (file-cat dir "trigon~.help.jmax"))
(help-patch "acos~" (file-cat dir "trigon~.help.jmax"))
(help-patch "atan~" (file-cat dir "trigon~.help.jmax"))
(help-patch "arctan2~" (file-cat dir "arctan2~.help.jmax"))
(help-patch "sinh~" (file-cat dir "trigon~.help.jmax"))
(help-patch "cosh~" (file-cat dir "trigon~.help.jmax"))
(help-patch "tanh~" (file-cat dir "trigon~.help.jmax"))

;; io (5)
(help-patch "adc~" (file-cat dir "adc~.help.jmax"))
(help-patch "dac~" (file-cat dir "adc~.help.jmax"))
(help-patch "print~" (file-cat dir "print~.help.jmax"))

;; misc math (7)
(help-patch "abs~" (file-cat dir "abs~.help.jmax"))
(help-patch "clip~" (file-cat dir "clip~.help.jmax"))
(help-patch "exp~" (file-cat dir "exp~.help.jmax"))
(help-patch "log10~" (file-cat dir "exp~.help.jmax"))
(help-patch "log~" (file-cat dir "exp~.help.jmax"))
(help-patch "rsqrt~" (file-cat dir "sqrt~.help.jmax"))
(help-patch "sqrt~" (file-cat dir "sqrt~.help.jmax"))

;; signal flow (6)
(help-patch "down~" (file-cat dir "down~.help.jmax"))
(help-patch "up~" (file-cat dir "down~.help.jmax"))
(help-patch "thrxw~" (file-cat dir "catch~.help.jmax"))
(help-patch "cxtch~" (file-cat dir "catch~.help.jmax"))
(help-patch "switch~" (file-cat dir "switch~.help.jmax"))
(help-patch "thru~" (file-cat dir "thru~.help.jmax"))

;; sampling (7)
(help-patch "table~" (file-cat dir "table~.help.jmax"))
(help-patch "samppeek~" (file-cat dir "samppeek~.help.jmax"))
(help-patch "sampread~" (file-cat dir "sampwrite~.help.jmax"))
(help-patch "sampwrite~" (file-cat dir "sampwrite~.help.jmax"))
(help-patch "tabcycle~" (file-cat dir "tabcycle~.help.jmax"))
(help-patch "tabpeek~" (file-cat dir "tabpeek~.help.jmax"))
(help-patch "tabpoke" (file-cat dir "tabpoke.help.jmax"))

;; delay lines (3)
(help-patch "delwrite~" (file-cat dir "delay~.help.jmax"))
(help-patch "delread~" (file-cat dir "delay~.help.jmax"))
(help-patch "vd~" (file-cat dir "delay~.help.jmax"))

;; fourier transformation (2)
(help-patch "fft~" (file-cat dir "fft~.help.jmax"))
(help-patch "ifft~" (file-cat dir "fft~.help.jmax"))

;; generators (5)
(help-patch "sig~" (file-cat dir "sig~.help.jmax"))
(help-patch "line~" (file-cat dir "line~.help.jmax"))
(help-patch "phasor~" (file-cat dir "phasor~.help.jmax"))
(help-patch "osc1~" (file-cat dir "osc1~.help.jmax"))
(help-patch "tab1~" (file-cat dir "osc1~.help.jmax"))
(help-patch "noise~" (file-cat dir "noise~.help.jmax"))

;; signal peep (7)
(help-patch "pitch~" (file-cat dir "pitch~.help.jmax"))
(help-patch "pt~" (file-cat dir "pt~.help.jmax"))
(help-patch "snapshot~" (file-cat dir "snapshot~.help.jmax"))
(help-patch "threshold~" (file-cat dir "threshold~.help.jmax"))
(help-patch "zerocross~" (file-cat dir "zerocross~.help.jmax"))
(help-patch "samplerate~" (file-cat dir "samplerate~.help.jmax"))
(help-patch "vectorsize~" (file-cat dir "samplerate~.help.jmax"))
