#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  

all_c: all
clean_c: clean


all:
	(cd src; $(MAKE) all)
.PHONY: all

clean:
	(cd src; $(MAKE) clean)
.PHONY: all
