#ifndef BISON_Y_TAB_H
# define BISON_Y_TAB_H

#ifndef YYSTYPE
typedef union {
  fts_atom_t a;
  pnode_t *n;
} yystype;
# define YYSTYPE yystype
# define YYSTYPE_IS_TRIVIAL 1
#endif
# define	FTS_TOKEN_INT	257
# define	FTS_TOKEN_FLOAT	258
# define	FTS_TOKEN_SYMBOL	259
# define	FTS_TOKEN_COLON	260
# define	FTS_TOKEN_PAR	261
# define	FTS_TOKEN_OPEN_PAR	262
# define	FTS_TOKEN_CLOSED_PAR	263
# define	FTS_TOKEN_CPAR	264
# define	FTS_TOKEN_OPEN_CPAR	265
# define	FTS_TOKEN_CLOSED_CPAR	266
# define	FTS_TOKEN_SQPAR	267
# define	FTS_TOKEN_OPEN_SQPAR	268
# define	FTS_TOKEN_CLOSED_SQPAR	269
# define	FTS_TOKEN_SEMI	270
# define	FTS_TOKEN_TUPLE	271
# define	FTS_TOKEN_EQUAL	272
# define	FTS_TOKEN_LOGICAL_OR	273
# define	FTS_TOKEN_LOGICAL_AND	274
# define	FTS_TOKEN_EQUAL_EQUAL	275
# define	FTS_TOKEN_NOT_EQUAL	276
# define	FTS_TOKEN_GREATER	277
# define	FTS_TOKEN_GREATER_EQUAL	278
# define	FTS_TOKEN_SMALLER	279
# define	FTS_TOKEN_SMALLER_EQUAL	280
# define	FTS_TOKEN_UMINUS	281
# define	FTS_TOKEN_UPLUS	282
# define	FTS_TOKEN_SHIFT_LEFT	283
# define	FTS_TOKEN_SHIFT_RIGHT	284
# define	FTS_TOKEN_PLUS	285
# define	FTS_TOKEN_MINUS	286
# define	FTS_TOKEN_TIMES	287
# define	FTS_TOKEN_DIV	288
# define	FTS_TOKEN_PERCENT	289
# define	FTS_TOKEN_LOGICAL_NOT	290
# define	FTS_TOKEN_POWER	291
# define	FTS_TOKEN_ARRAY_INDEX	292
# define	FTS_TOKEN_DOT	293
# define	FTS_TOKEN_DOLLAR	294


#endif /* not BISON_Y_TAB_H */
