#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	FTS_TOKEN_INT	257
#define	FTS_TOKEN_FLOAT	258
#define	FTS_TOKEN_SYMBOL	259
#define	FTS_TOKEN_SEMI	260
#define	FTS_TOKEN_OPEN_PAR	261
#define	FTS_TOKEN_CLOSED_PAR	262
#define	FTS_TOKEN_OPEN_SQPAR	263
#define	FTS_TOKEN_CLOSED_SQPAR	264
#define	FTS_TOKEN_SPACE	265
#define	FTS_TOKEN_EQUAL	266
#define	FTS_TOKEN_LOGICAL_OR	267
#define	FTS_TOKEN_LOGICAL_AND	268
#define	FTS_TOKEN_EQUAL_EQUAL	269
#define	FTS_TOKEN_NOT_EQUAL	270
#define	FTS_TOKEN_GREATER	271
#define	FTS_TOKEN_GREATER_EQUAL	272
#define	FTS_TOKEN_SMALLER	273
#define	FTS_TOKEN_SMALLER_EQUAL	274
#define	FTS_TOKEN_SHIFT_LEFT	275
#define	FTS_TOKEN_SHIFT_RIGHT	276
#define	FTS_TOKEN_PLUS	277
#define	FTS_TOKEN_MINUS	278
#define	FTS_TOKEN_TIMES	279
#define	FTS_TOKEN_DIV	280
#define	FTS_TOKEN_PERCENT	281
#define	FTS_TOKEN_UNARY_MINUS	282
#define	FTS_TOKEN_UNARY_PLUS	283
#define	FTS_TOKEN_LOGICAL_NOT	284
#define	FTS_TOKEN_ARRAY_INDEX	285
#define	FTS_TOKEN_DOT	286
#define	FTS_TOKEN_DOLLAR	287

