#ifndef YYSTYPE
#define YYSTYPE int
#endif
#define	FTS_TOKEN_INT	257
#define	FTS_TOKEN_FLOAT	258
#define	FTS_TOKEN_SYMBOL	259
#define	FTS_TOKEN_DOLLAR	260
#define	FTS_TOKEN_SEMICOLON	261
#define	FTS_TOKEN_LPAR	262
#define	FTS_TOKEN_RPAR	263
#define	FTS_TOKEN_DOT	264
#define	FTS_TOKEN_LSBRA	265
#define	FTS_TOKEN_RSBRA	266

