#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../../..
PACKAGE_DIR = ircam/jmax/editors/ermes/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
.PHONY: all


ErmesConnectCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesConnectCmd.java)
.PHONY: ErmesConnectCmd

ErmesDisconnectCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesDisconnectCmd.java)
.PHONY: ErmesDisconnectCmd

ErmesElementsCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesElementsCmd.java)
.PHONY: ErmesElementsCmd

ErmesGraphicsOffCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesGraphicsOffCmd.java)
.PHONY: ErmesGraphicsOffCmd

ErmesGraphicsOnCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesGraphicsOnCmd.java)
.PHONY: ErmesGraphicsOnCmd

ErmesObjDeleteCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjDeleteCmd.java)
.PHONY: ErmesObjDeleteCmd

ErmesObjNewObjCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjNewObjCmd.java)
.PHONY: ErmesObjNewObjCmd

ErmesObjectGetPositionXCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectGetPositionXCmd.java)
.PHONY: ErmesObjectGetPositionXCmd

ErmesObjectGetPositionYCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectGetPositionYCmd.java)
.PHONY: ErmesObjectGetPositionYCmd

ErmesObjectGetSizeHCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectGetSizeHCmd.java)
.PHONY: ErmesObjectGetSizeHCmd

ErmesObjectGetSizeWCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectGetSizeWCmd.java)
.PHONY: ErmesObjectGetSizeWCmd

ErmesObjectSetPositionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectSetPositionCmd.java)
.PHONY: ErmesObjectSetPositionCmd

ErmesObjectSetSizeCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesObjectSetSizeCmd.java)
.PHONY: ErmesObjectSetSizeCmd

ErmesPatNewCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesPatNewCmd.java)
.PHONY: ErmesPatNewCmd

ErmesSelectedCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesSelectedCmd.java)
.PHONY: ErmesSelectedCmd

ErmesShowCmd:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) ErmesShowCmd.java)
.PHONY: ErmesShowCmd

TclErmesPackage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) TclErmesPackage.java)
.PHONY: TclErmesPackage


include $(ROOTDIR)/java/Makefiles/Makefile.misc

