#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../../..
PACKAGE_DIR = ircam/jmax/editors/ermes/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: $(CLASS_FILES)

include $(ROOTDIR)/java/Makefiles/Makefile.misc
