#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../../..
PACKAGE_DIR = ircam/jmax/editors/ermes/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	javac $(JFLAGS) $(SOURCES)
.PHONY: all


ErmesConnectCmd:
	javac $(JFLAGS) ErmesConnectCmd.java
.PHONY: ErmesConnectCmd

ErmesDisconnectCmd:
	javac $(JFLAGS) ErmesDisconnectCmd.java
.PHONY: ErmesDisconnectCmd

ErmesElementsCmd:
	javac $(JFLAGS) ErmesElementsCmd.java
.PHONY: ErmesElementsCmd

ErmesGraphicsOffCmd:
	javac $(JFLAGS) ErmesGraphicsOffCmd.java
.PHONY: ErmesGraphicsOffCmd

ErmesGraphicsOnCmd:
	javac $(JFLAGS) ErmesGraphicsOnCmd.java
.PHONY: ErmesGraphicsOnCmd

ErmesObjDeleteCmd:
	javac $(JFLAGS) ErmesObjDeleteCmd.java
.PHONY: ErmesObjDeleteCmd

ErmesObjNewObjCmd:
	javac $(JFLAGS) ErmesObjNewObjCmd.java
.PHONY: ErmesObjNewObjCmd

ErmesObjectGetPositionXCmd:
	javac $(JFLAGS) ErmesObjectGetPositionXCmd.java
.PHONY: ErmesObjectGetPositionXCmd

ErmesObjectGetPositionYCmd:
	javac $(JFLAGS) ErmesObjectGetPositionYCmd.java
.PHONY: ErmesObjectGetPositionYCmd

ErmesObjectGetSizeHCmd:
	javac $(JFLAGS) ErmesObjectGetSizeHCmd.java
.PHONY: ErmesObjectGetSizeHCmd

ErmesObjectGetSizeWCmd:
	javac $(JFLAGS) ErmesObjectGetSizeWCmd.java
.PHONY: ErmesObjectGetSizeWCmd

ErmesObjectSetPositionCmd:
	javac $(JFLAGS) ErmesObjectSetPositionCmd.java
.PHONY: ErmesObjectSetPositionCmd

ErmesObjectSetSizeCmd:
	javac $(JFLAGS) ErmesObjectSetSizeCmd.java
.PHONY: ErmesObjectSetSizeCmd

ErmesPatNewCmd:
	javac $(JFLAGS) ErmesPatNewCmd.java
.PHONY: ErmesPatNewCmd

ErmesSelectedCmd:
	javac $(JFLAGS) ErmesSelectedCmd.java
.PHONY: ErmesSelectedCmd

ErmesShowCmd:
	javac $(JFLAGS) ErmesShowCmd.java
.PHONY: ErmesShowCmd

TclErmesPackage:
	javac $(JFLAGS) TclErmesPackage.java
.PHONY: TclErmesPackage


include $(ROOTDIR)/java/Makefiles/Makefile.misc

