## ispw jimmies lib abstraction table

abstraction 2pole~ $dir/2pole~.abs
abstraction adc1~ $dir/adc1~.abs
abstraction apass1~ $dir/apass1~.abs
abstraction apass2~ $dir/apass2~.abs
abstraction bpass1~ $dir/bpass1~.abs
abstraction bstop1~ $dir/bstop1~.abs
abstraction comb1~ $dir/comb1~.abs
abstraction comb2~ $dir/comb2~.abs
abstraction complex-mod~ $dir/complex-mod~.abs
abstraction db1 $dir/db1.abs
abstraction delay1~ $dir/delay1~.abs
abstraction envfol1~ $dir/envfol1~.abs
abstraction flange1~ $dir/flange1~.abs
abstraction fshift1~ $dir/fshift1~.abs
abstraction gain1~ $dir/gain1~.abs
abstraction gain2~ $dir/gain2~.abs
abstraction harmv1~ $dir/harmv1~.abs
abstraction hilbert~ $dir/hilbert~.abs
abstraction hpass1~ $dir/hpass1~.abs
abstraction hpass2~ $dir/hpass2~.abs
abstraction hz->radians $dir/hz->radians.abs
abstraction lpass1~ $dir/lpass1~.abs
abstraction lpass2~ $dir/lpass2~.abs
abstraction mute1~ $dir/mute1~.abs
abstraction peak~ $dir/peak~.abs
abstraction peq1~ $dir/peq1~.abs
abstraction peq2~ $dir/peq2~.abs
abstraction peqbank1~ $dir/peqbank1~.abs
abstraction phaseshift1~ $dir/phaseshift1~.abs
abstraction probe1~ $dir/probe1~.abs
abstraction qgain1~ $dir/qgain1~.abs
abstraction qpan1~ $dir/qpan1~.abs
abstraction radians->hz $dir/radians->hz.abs
abstraction rev1~ $dir/rev1~.abs
abstraction rev4~ $dir/rev4~.abs
abstraction rmod1~ $dir/rmod1~.abs
abstraction rms1~ $dir/rms1~.abs
abstraction sampv1~ $dir/sampv1~.abs
abstraction stchorus1~ $dir/stchorus1~.abs
abstraction stgain1~ $dir/stgain1~.abs
abstraction stharms1~ $dir/stharms1~.abs
abstraction stpan1~ $dir/stpan1~.abs
abstraction tone1~ $dir/tone1~.abs
abstraction vu1~ $dir/vu1~.abs
