/* config.h
 *
 * This should be a file generated by configure, as in glib
 *
 * BUT: Mac OS X and Windows do not have a configure script.
 * So ???
 */

/* Macros for pointer to int conversion.
*/
#define POINTER_TO_UINT(p) ( (unsigned int) (p) )
#define UINT_TO_POINTER(u) ( (void *) (u) )

