
all:
	(cd sys; $(MAKE) all)
	(cd lang; $(MAKE) all)
	(cd runtime; $(MAKE) all)
	(cd tiles; $(MAKE) all)
.PHONY: all

clean:
	(cd sys; $(MAKE) clean)
	(cd lang; $(MAKE) clean)
	(cd runtime; $(MAKE) clean)
	(cd tiles; $(MAKE) clean)
.PHONY: all
