#!/bin/sh

#
# This scripts builds a rpm for jMax. 
# It requires that the sources are located in ../..
# 
# The optional argument is the architecture of the rpm
# (i386, i686, ppc)
#

if [ $# -ge 1 ]
then
    ARCH=$1
else
    ARCH=`arch`
fi

# The root directory of sources
ROOT_DIR=../..

VERSION=`cut -f1 -d\  $ROOT_DIR/VERSION`
DISTFILE=$ROOT_DIR/../jmax-$VERSION-src.tar.gz
cp -fv $DISTFILE /usr/src/redhat/SOURCES
cp -fv jmax.spec /usr/src/redhat/SPECS

cd /usr/src/redhat/SPECS
rpm -ba --target $ARCH jmax.spec
cp /usr/src/redhat/RPMS/$ARCH/jmax-$VERSION*.$ARCH.rpm $ROOT_DIR/..

