#!/bin/sh
# This scripts builds a rpm for jMax. 
# 

# Note: on Mandrake, rpm building directories are in /usr/src/RPM...
# add an option to specify it

JMAX_VERSION=2.5.3

ARCH=`arch`

DISTFILE=jmax-$JMAX_VERSION-src.tar.gz
BINARY_RPM=jmax-$JMAX_VERSION*.$ARCH.rpm 
SOURCE_RPM=jmax-$JMAX_VERSION*.src.rpm

cp -fv $DISTFILE /usr/src/redhat/SOURCES
cp -fv jmax.spec /usr/src/redhat/SPECS

(cd /usr/src/redhat/SPECS ; rpm -ba --target=$ARCH jmax.spec )

cp /usr/src/redhat/RPMS/$ARCH/$BINARY_RPM .
cp /usr/src/redhat/SRPMS/$SOURCE_RPM .
chmod 644 $BINARY_RPM $SOURCE_RPM
