#!/bin/sh

#
# This scripts builds a rpm for jMax. 
# It requires that the sources are located in ../..
# 
# The optional argument is the architecture of the rpm
# (i386, i686, ppc)
#

# Note: on Mandrake, rpm building directories are in /usr/src/RPM...
# add an option to specify it


if [ $# -ge 1 ]
then
    ARCH=$1
else
    ARCH=`arch`
fi

# The root directory of sources
ROOT_DIR=../..

. $ROOT_DIR/VERSION
JMAX_VERSION=${JMAX_MAJOR_VERSION}.${JMAX_MINOR_VERSION}.${JMAX_PATCH_VERSION}${JMAX_VERSION_STATUS}
DISTFILE=$ROOT_DIR/../jmax-$JMAX_VERSION-src.tar.gz
cp -fv $DISTFILE /usr/src/redhat/SOURCES
cp -fv jmax.spec /usr/src/redhat/SPECS

(cd /usr/src/redhat/SPECS ; rpm -ba --target=$ARCH jmax.spec )
cp /usr/src/redhat/RPMS/$ARCH/jmax-$JMAX_VERSION*.$ARCH.rpm $ROOT_DIR/..
cp /usr/src/redhat/SRPMS/jmax-$JMAX_VERSION*.src.rpm $ROOT_DIR/..
chmod 644 $ROOT_DIR/../jmax-$JMAX_VERSION*.$ARCH.rpm $ROOT_DIR/../jmax-$JMAX_VERSION*.src.rpm
