helpPatch const $dir/const.help.jmax
helpPatch print $dir/print.help.jmax
helpPatch inlet $dir/inout.help.jmax
helpPatch outlet $dir/inout.help.jmax
helpPatch label $dir/inout.help.jmax
helpPatch bus $dir/bus.help.jmax
helpPatch throw $dir/bus.help.jmax
helpPatch catch $dir/bus.help.jmax
helpPatch bus~ $dir/bus~.help.jmax
helpPatch throw~ $dir/bus~.help.jmax
helpPatch catch~ $dir/bus~.help.jmax
