#!/bin/sh

#
# This scripts builds a rpm for jMax. 
# It requires that the sources are located in ../..
# 
# The mandatory argument is the architecture of the rpm
# (i386, i686, ppc)
#

ARCH=$1

VERSION=`cat ../VERSION`
DISTFILE=../../jmax-$VERSION-src.tar.gz
cp -fv $DISTFILE /usr/src/redhat/SOURCES
cp -fv jmax.spec /usr/src/redhat/SPECS

cd /usr/src/redhat/SPECS
rpm -ba --target $ARCH jmax.spec

