#!/bin/sh
ARCH=$1

VERSION=`cat ../VERSION`
DISTFILE=../../jmax-$VERSION-src.tar.gz
cp -fv $DISTFILE /usr/src/redhat/SOURCES
cp -fv jmax.spec /usr/src/redhat/SPECS

cd /usr/src/redhat/SPECS
rpm -ba --target $ARCH jmax.spec

