#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  Authors: Maurizio De Cecco, Francois Dechelle, Enzo Maggi, Norbert Schnell.
#
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  
#


ROOTDIR = ../../../../..
PACKAGE_DIR = ircam/jmax/fts

include $(ROOTDIR)/java/Makefiles/Makefile.common

INCLUDE_PATH := $(JAVA_SRC_ROOT)/$(PACKAGE_DIR)
include Sources2

all: 
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
.PHONY: all

Fts:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) Fts.java)
.PHONY: Fts

FtsAbstractionObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsAbstractionObject.java)
.PHONY: FtsAbstractionObject

FtsAtomList:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsAtomList.java)
.PHONY: FtsAtomList

FtsBmaxRemoteDocumentHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsBmaxRemoteDocumentHandler.java)
.PHONY: FtsBmaxRemoteDocumentHandler

FtsClientProtocol:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsClientProtocol.java)
.PHONY: FtsClientProtocol

FtsCommentObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsCommentObject.java)
.PHONY: FtsCommentObject

FtsConnection:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsConnection.java)
.PHONY: FtsConnection

FtsContainerObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsContainerObject.java)
.PHONY: FtsContainerObject


FtsDotPatRemoteDocumentHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDotPatRemoteDocumentHandler.java)
.PHONY: FtsDotPatRemoteDocumentHandler

FtsError:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsError.java)
.PHONY: FtsError

FtsErrorStreamer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsErrorStreamer.java)
.PHONY: FtsErrorStreamer

FtsException:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsException.java)
.PHONY: FtsException

FtsHelpPatchTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsHelpPatchTable.java)
.PHONY: FtsHelpPatchTable

FtsInletObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsInletObject.java)
.PHONY: FtsInletObject

FtsIntegerVector:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsIntegerVector.java)
.PHONY: FtsIntegerVector

FtsMessage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessage.java)
.PHONY: FtsMessage

FtsMessageHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessageHandler.java)
.PHONY: FtsMessageHandler

FtsMessageObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessageObject.java)
.PHONY: FtsMessageObject

FtsModule:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsModule.java)
.PHONY: FtsModule

FtsObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsObject.java)
.PHONY: FtsObject

FtsObjectWithData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsObjectWithData.java)
.PHONY: FtsObjectWithData

FtsOutletObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsOutletObject.java)
.PHONY: FtsOutletObject

FtsParse:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsParse.java)
.PHONY: FtsParse

FtsPatcherDocument:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatcherDocument.java)
.PHONY: FtsPatcherDocument

FtsPatcherData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatcherData.java)
.PHONY: FtsPatcherData

FtsPatcherDocumentType:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatcherDocumentType.java)
.PHONY: FtsPatcherDocumentType

FtsPatcherObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatcherObject.java)
.PHONY: FtsPatcherObject

FtsStream:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsStream.java)
.PHONY: FtsStream

FtsPropertyDescriptor:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPropertyDescriptor.java)
.PHONY: FtsPropertyDescriptor

FtsPropertyHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPropertyHandler.java)
.PHONY: FtsPropertyHandler

FtsReferenceURLTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsReferenceURLTable.java)
.PHONY: FtsReferenceURLTable

FtsSelection:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSelection.java)
.PHONY: FtsSelection

FtsServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsServer.java)
.PHONY: FtsServer

FtsSocketClientServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketClientServer.java)
.PHONY: FtsSocketClientServer

FtsSocketPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketPort.java)
.PHONY: FtsSocketPort

FtsSocketServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketServer.java)
.PHONY: FtsSocketServer

FtsSocketServerPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketServerPort.java)
.PHONY: FtsSocketServerPort

FtsDatagramPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDatagramPort.java)
.PHONY: FtsDatagramPort

FtsRexecDatagramPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsRexecDatagramPort.java)
.PHONY: FtsRexecDatagramPort

FtsDatagramClientPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDatagramClientPort.java)
.PHONY: FtsDatagramClientPort

FtsDatagramServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDatagramServer.java)
.PHONY: FtsDatagramServer


FtsRexecDatagramServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsRexecDatagramServer.java)
.PHONY: FtsRexecDatagramServer

FtsStandardObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsStandardObject.java)
.PHONY: FtsStandardObject

FtsSubProcessPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSubProcessPort.java)
.PHONY: FtsSubProcessPort

FtsSubProcessServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSubProcessServer.java)
.PHONY: FtsSubProcessServer

FtsTableObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTableObject.java)
.PHONY: FtsTableObject

FtsTclPropertyParser:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTclPropertyParser.java)
.PHONY: FtsTclPropertyParser

FtsTemplateTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTemplateTable.java)
.PHONY: FtsTemplateTable

FtsUpdateGroupListener:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsUpdateGroupListener.java)
.PHONY: FtsUpdateGroupListener

FtsRemoteData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsRemoteData.java)
.PHONY: FtsRemoteData

FtsRemoteUndoableData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsRemoteUndoableData.java)
.PHONY: FtsRemoteUndoableData

FtsRemoteMetaData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsRemoteMetaData.java)
.PHONY: FtsRemoteMetaData

FtsObjectSet:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsObjectSet.java)
.PHONY: FtsObjectSet




include $(ROOTDIR)/java/Makefiles/Makefile.misc




