#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../..
PACKAGE_DIR = ircam/jmax/fts

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) $(SOURCES))
	(cd tcl; $(MAKE) all)
.PHONY: all

FtsModule:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsModule.java)
.PHONY: FtsModule

FtsAbstractionTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsAbstractionTable.java)
.PHONY: FtsAbstractionTable

FtsClientProtocol:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsClientProtocol.java)
.PHONY: FtsClientProtocol

FtsConnection:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsConnection.java)
.PHONY: FtsConnection

FtsErrorStreamer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsErrorStreamer.java)
.PHONY: FtsErrorStreamer


FtsHelpPatchTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsHelpPatchTable.java)
.PHONY: FtsHelpPatchTable

FtsMessage:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessage.java)
.PHONY: FtsMessage

FtsMessageHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessageHandler.java)
.PHONY: FtsMessageHandler

FtsObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsObject.java)
.PHONY: FtsObject

FtsPatcherObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatcherObject.java)
.PHONY: FtsPatcherObject

FtsInletObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsInletObject.java)
.PHONY: FtsInletObject

FtsOutletObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsOutletObject.java)
.PHONY: FtsOutletObject

FtsContainerObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsContainerObject.java)
.PHONY: FtsContainerObject

FtsAbstractionObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsAbstractionObject.java)
.PHONY: FtsAbstractionObject

FtsTemplateObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTemplateObject.java)
.PHONY: FtsTemplateObject

FtsStandardObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsStandardObject.java)
.PHONY: FtsStandardObject

FtsMessageObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsMessageObject.java)
.PHONY: FtsMessageObject

FtsCommentObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsCommentObject.java)
.PHONY: FtsCommentObject

FtsDeclarationObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDeclarationObject.java)
.PHONY: FtsDeclarationObject

FtsValueObject:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsValueObject.java)
.PHONY: FtsValueObject

FtsParse:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsParse.java)
.PHONY: FtsParse

FtsPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPort.java)
.PHONY: FtsPort

FtsPropertyHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPropertyHandler.java)
.PHONY: FtsPropertyHandler

FtsReferenceURLTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsReferenceURLTable.java)
.PHONY: FtsReferenceURLTable

FtsSaveStream:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSaveStream.java)
.PHONY: FtsSaveStream

FtsServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsServer.java)
.PHONY: FtsServer

FtsSocketClientServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketClientServer.java)
.PHONY: FtsSocketClientServer

FtsSocketPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketPort.java)
.PHONY: FtsSocketPort

FtsSocketServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketServer.java)
.PHONY: FtsSocketServer

FtsSocketServerPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSocketServerPort.java)
.PHONY: FtsSocketServerPort

FtsSubProcessPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSubProcessPort.java)
.PHONY: FtsSubProcessPort

FtsSubProcessServer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsSubProcessServer.java)
.PHONY: FtsSubProcessServer

FtsTemplateTable:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTemplateTable.java)
.PHONY: FtsTemplateTable

FtsDotPatParser:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDotPatParser.java)
.PHONY: FtsDotPatParser

FtsDotPatTokenizer:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDotPatTokenizer.java)
.PHONY: FtsDotPatTokenizer

FtsLocator:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsLocator.java)
.PHONY: FtsLocator

FtsDotPatFileDataHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsDotPatFileDataHandler.java )
.PHONY: FtsDotPatFileDataHandler

FtsTpaFileDataHandler:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTpaFileDataHandler.java)
.PHONY: FtsTpaFileDataHandler

FtsPatchData:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatchData.java)
.PHONY: FtsPatchData

FtsPatchDataType:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPatchDataType.java)
.PHONY: FtsPatchDataType

FtsPropertyDescriptor:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsPropertyDescriptor.java)
.PHONY: FtsPropertyDescriptor

FtsTclPropertyParser:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsTclPropertyParser.java)
.PHONY: FtsTclPropertyParser

FtsUpdateGroupListener:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsUpdateGroupListener.java)
.PHONY: FtsUpdateGroupListener

FtsParseToPort:
	(CLASSPATH=$(JMAX_CLASSPATH) ; export CLASSPATH ; javac $(JFLAGS) FtsParseToPort.java)
.PHONY: FtsParseToPort



include $(ROOTDIR)/java/Makefiles/Makefile.misc




