#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../..
PACKAGE_DIR = ircam/jmax/editors

include $(ROOTDIR)/java/Makefiles/Makefile.common


all: 
	(cd console  ; $(MAKE) all )
	(cd control  ; $(MAKE) all )
	(cd ermes    ; $(MAKE) all )
.PHONY: all

include $(ROOTDIR)/java/Makefiles/Makefile.misc


