#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  


MODE_CFLAGS = $(ARCH_OPT_CFLAGS) -DOPTIMIZE 
MODE_LDFLAGS = $(ARCH_OPT_LDFLAGS)
MODE_SOFLAGS = $(ARCH_OPT_SOFLAGS)


