#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../..
PACKAGE_DIR = ircam/jmax/fts/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	javac $(JFLAGS) $(SOURCES)
.PHONY: all


FtsAbstractionCmd:
	javac $(JFLAGS) FtsAbstractionCmd.java
.PHONY: FtsAbstractionCmd

FtsAddListenerCmd:
	javac $(JFLAGS) FtsAddListenerCmd.java
.PHONY: FtsAddListenerCmd

FtsClassNameCmd:
	javac $(JFLAGS) FtsClassNameCmd.java
.PHONY: FtsClassNameCmd

FtsConnectionCmd:
	javac $(JFLAGS) FtsConnectionCmd.java
.PHONY: FtsConnectionCmd

FtsDeclareCmd:
	javac $(JFLAGS) FtsDeclareCmd.java
.PHONY: FtsDeclareCmd

FtsHelpPatchCmd:
	javac $(JFLAGS) FtsHelpPatchCmd.java
.PHONY: FtsHelpPatchCmd

FtsInitCmd:
	javac $(JFLAGS) FtsInitCmd.java
.PHONY: FtsInitCmd

FtsMessCmd:
	javac $(JFLAGS) FtsMessCmd.java
.PHONY: FtsMessCmd

FtsObjectCmd:
	javac $(JFLAGS) FtsObjectCmd.java
.PHONY: FtsObjectCmd

FtsPatcherCmd:
	javac $(JFLAGS) FtsPatcherCmd.java
.PHONY: FtsPatcherCmd

FtsReferenceURLCmd:
	javac $(JFLAGS) FtsReferenceURLCmd.java
.PHONY: FtsReferenceURLCmd

FtsSetPropertyCmd:
	javac $(JFLAGS) FtsSetPropertyCmd.java
.PHONY: FtsSetPropertyCmd

FtsSyncCmd:
	javac $(JFLAGS) FtsSyncCmd.java
.PHONY: FtsSyncCmd

FtsTemplateCmd:
	javac $(JFLAGS) FtsTemplateCmd.java
.PHONY: FtsTemplateCmd

FtsUcsCmd:
	javac $(JFLAGS) FtsUcsCmd.java
.PHONY: FtsUcsCmd

FtsVersionCmd:
	javac $(JFLAGS) FtsVersionCmd.java
.PHONY: FtsVersionCmd

TclFtsPackage:
	javac $(JFLAGS) TclFtsPackage.java
.PHONY: TclFtsPackage

include $(ROOTDIR)/java/Makefiles/Makefile.misc
