#
#                      FTS 2.x makefile for GNU Make
#
#			Copyright (c) 1997 by IRCAM
#			    All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                              manager@ircam.fr
#
#
#


ROOTDIR = ../../../../../..
PACKAGE_DIR = ircam/jmax/fts/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common
include Sources

all: 
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) $(SOURCES))
.PHONY: all


FtsAbstractionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAbstractionCmd.java)
.PHONY: FtsAbstractionCmd

FtsAddListenerCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAddListenerCmd.java)
.PHONY: FtsAddListenerCmd

FtsClassNameCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsClassNameCmd.java)
.PHONY: FtsClassNameCmd

FtsConnectionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsConnectionCmd.java)
.PHONY: FtsConnectionCmd

FtsDeclareCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsDeclareCmd.java)
.PHONY: FtsDeclareCmd

FtsHelpPatchCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsHelpPatchCmd.java)
.PHONY: FtsHelpPatchCmd

FtsMessCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsMessCmd.java)
.PHONY: FtsMessCmd

FtsObjectCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsObjectCmd.java)
.PHONY: FtsObjectCmd

FtsPatcherCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsPatcherCmd.java)
.PHONY: FtsPatcherCmd

FtsCommentCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsCommentCmd.java)
.PHONY: FtsCommentCmd

FtsOutletCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsOutletCmd.java)
.PHONY: FtsOutletCmd

FtsInletCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsInletCmd.java)
.PHONY: FtsInletCmd

FtsReferenceURLCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsReferenceURLCmd.java)
.PHONY: FtsReferenceURLCmd

FtsSetPropertyCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsSetPropertyCmd.java)
.PHONY: FtsSetPropertyCmd

FtsSyncCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsSyncCmd.java)
.PHONY: FtsSyncCmd

FtsTemplateCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsTemplateCmd.java)
.PHONY: FtsTemplateCmd

FtsUcsCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsUcsCmd.java)
.PHONY: FtsUcsCmd

FtsVersionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsVersionCmd.java)
.PHONY: FtsVersionCmd

FtsGetObjectByNameCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsGetObjectByNameCmd.java)
.PHONY: FtsGetObjectByNameCmd

TclFtsPackage:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) TclFtsPackage.java)
.PHONY: TclFtsPackage

include $(ROOTDIR)/java/Makefiles/Makefile.misc
