# 
# jMax
# Copyright (C) 1994, 1995, 1998, 1999 by IRCAM-Centre Georges Pompidou, Paris, France.
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# See file LICENSE for further informations on licensing terms.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
# 
# Based on Max/ISPW by Miller Puckette.
#
# Authors: Maurizio De Cecco, Francois Dechelle, Enzo Maggi, Norbert Schnell.



ROOTDIR = ../../../../../..
PACKAGE_DIR = ircam/jmax/fts/tcl

include $(ROOTDIR)/java/Makefiles/Makefile.common

INCLUDE_PATH := $(JAVA_SRC_ROOT)/$(PACKAGE_DIR)
include $(INCLUDE_PATH)/Sources2

all: 
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) $(SOURCES))
.PHONY: all


FtsAbstractionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAbstractionCmd.java)
.PHONY: FtsAbstractionCmd

FtsAbstractionPathCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAbstractionPathCmd.java)
.PHONY: FtsAbstractionPathCmd

FtsAddListenerCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAddListenerCmd.java)
.PHONY: FtsAddListenerCmd

FtsAtomListCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsAtomListCmd.java)
.PHONY: FtsAtomListCmd

FtsClassNameCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsClassNameCmd.java)
.PHONY: FtsClassNameCmd

FtsCommentCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsCommentCmd.java)
.PHONY: FtsCommentCmd

FtsConnectionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsConnectionCmd.java)
.PHONY: FtsConnectionCmd

FtsDeclareCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsDeclareCmd.java)
.PHONY: FtsDeclareCmd

FtsGetObjectByNameCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsGetObjectByNameCmd.java)
.PHONY: FtsGetObjectByNameCmd

FtsHelpPatchCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsHelpPatchCmd.java)
.PHONY: FtsHelpPatchCmd

FtsInletCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsInletCmd.java)
.PHONY: FtsInletCmd

FtsIntegerVectorCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsIntegerVectorCmd.java)
.PHONY: FtsIntegerVectorCmd

FtsMessCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsMessCmd.java)
.PHONY: FtsMessCmd

FtsObjectCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsObjectCmd.java)
.PHONY: FtsObjectCmd

FtsOutletCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsOutletCmd.java)
.PHONY: FtsOutletCmd

FtsPatcherCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsPatcherCmd.java)
.PHONY: FtsPatcherCmd

FtsReferenceURLCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsReferenceURLCmd.java)
.PHONY: FtsReferenceURLCmd

FtsSetDataCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsSetDataCmd.java)
.PHONY: FtsSetDataCmd

FtsSetPropertyCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsSetPropertyCmd.java)
.PHONY: FtsSetPropertyCmd

FtsSyncCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsSyncCmd.java)
.PHONY: FtsSyncCmd

FtsTemplateCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsTemplateCmd.java)
.PHONY: FtsTemplateCmd

FtsUcsCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsUcsCmd.java)
.PHONY: FtsUcsCmd

FtsVersionCmd:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) FtsVersionCmd.java)
.PHONY: FtsVersionCmd

TclFtsPackage:
	(CLASSPATH=$(JMAX_CLASSPATH); export CLASSPATH;  javac $(JFLAGS) TclFtsPackage.java)
.PHONY: TclFtsPackage


include $(ROOTDIR)/java/Makefiles/Makefile.misc
