// DO NOT EDIT THIS FILE: it is generated automatically by the script make-new-version''
package ircam.jmax;

public class MaxVersion
{
  static String getMaxVersion()
  {
    return "jMax version 2.1.3";
  } 
}
