// DO NOT EDIT THIS FILE: it is generated automatically by the script jmax-make-new-version''

package ircam.jmax;

public class MaxVersion {
  public static String getMaxVersion()
  {
     return "jMax version 2.4.0";
  } 
}
