
all:
	(cd sched; $(MAKE) all)
	(cd time; $(MAKE) all)
	(cd files; $(MAKE) all)
	(cd midi; $(MAKE) all)
	(cd audio; $(MAKE) all)
	(cd client; $(MAKE) all)
	(cd devices; $(MAKE) all)
.PHONY: all

clean:
	(cd sched; $(MAKE) clean)
	(cd time; $(MAKE) clean)
	(cd files; $(MAKE) clean)
	(cd midi; $(MAKE) clean)
	(cd audio; $(MAKE) clean)
	(cd client; $(MAKE) clean)
	(cd devices; $(MAKE) clean)
.PHONY: all
