#
#  jMax
#  
#  Copyright (C) 1999 by IRCAM
#  All rights reserved.
#  
#  This program may be used and distributed under the terms of the 
#  accompanying LICENSE.
# 
#  This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
#  for DISCLAIMER OF WARRANTY.
#  

all:
	(cd sched; $(MAKE) all)
	(cd time; $(MAKE) all)
	(cd files; $(MAKE) all)
	(cd midi; $(MAKE) all)
	(cd audio; $(MAKE) all)
	(cd client; $(MAKE) all)
	(cd devices; $(MAKE) all)
.PHONY: all

clean:
	(cd sched; $(MAKE) clean)
	(cd time; $(MAKE) clean)
	(cd files; $(MAKE) clean)
	(cd midi; $(MAKE) clean)
	(cd audio; $(MAKE) clean)
	(cd client; $(MAKE) clean)
	(cd devices; $(MAKE) clean)
.PHONY: all
