;;
;; help declarations for the ispw control classes
;;

;; logic operators (4)
(help-patch "|" (file-cat dir "help" "control" "logic.help.jmax"))
(help-patch "||" (file-cat dir "help" "control" "logic.help.jmax"))
(help-patch "&&" (file-cat dir "help" "control" "logic.help.jmax"))
(help-patch "&" (file-cat dir "help" "control" "logic.help.jmax"))

;; comparison operators (6)
(help-patch "<=" (file-cat dir "help" "control" "compare.help.jmax"))
(help-patch "==" (file-cat dir "help" "control" "compare.help.jmax"))
(help-patch ">" (file-cat dir "help" "control" "compare.help.jmax"))
(help-patch ">=" (file-cat dir "help" "control" "compare.help.jmax"))
(help-patch "!=" (file-cat dir "help" "control" "compare.help.jmax"))
(help-patch "<" (file-cat dir "help" "control" "compare.help.jmax"))

;; arithmetics (6)
(help-patch "%" (file-cat dir "help" "control" "arith.help.jmax"))
(help-patch "*" (file-cat dir "help" "control" "arith.help.jmax"))
(help-patch "+" (file-cat dir "help" "control" "arith.help.jmax"))
(help-patch "-" (file-cat dir "help" "control" "arith.help.jmax"))
(help-patch "inv*" (file-cat dir "help" "control" "arith.help.jmax"))
(help-patch "inv+" (file-cat dir "help" "control" "arith.help.jmax"))

;;shifting operators (2)
(help-patch "<<" (file-cat dir "help" "control" "shift.help.jmax"))
(help-patch ">>" (file-cat dir "help" "control" "shift.help.jmax"))

;; misc math (10)
(help-patch "abs" (file-cat dir "help" "control" "abs.help.jmax"))
(help-patch "accum" (file-cat dir "help" "control" "accum.help.jmax"))
(help-patch "clip" (file-cat dir "help" "control" "clip.help.jmax"))
(help-patch "expr" (file-cat dir "help" "control" "expr.help.jmax"))
(help-patch "exscale" (file-cat dir "help" "control" "exscale.help.jmax"))
(help-patch "ftom" (file-cat dir "help" "control" "ftom.help.jmax"))
(help-patch "linedrive" (file-cat dir "help" "control" "linedrive.help.jmax"))
(help-patch "logscale" (file-cat dir "help" "control" "exscale.help.jmax"))
(help-patch "mtof" (file-cat dir "help" "control" "mtof.help.jmax"))
(help-patch "scale" (file-cat dir "help" "control" "scale.help.jmax"))


;; data (7)
(help-patch "bag" (file-cat dir "help" "control" "bag.help.jmax"))
(help-patch "float" (file-cat dir "help" "control" "float.help.jmax"))
(help-patch "funbuff" (file-cat dir "help" "control" "funbuff.help.jmax"))
(help-patch "int" (file-cat dir "help" "control" "int.help.jmax"))
(help-patch "pbank" (file-cat dir "help" "control" "pbank.help.jmax"))
(help-patch "table" (file-cat dir "help" "control" "table.help.jmax"))
(help-patch "value" (file-cat dir "help" "control" "value.help.jmax"))

;; lists (3)
(help-patch "pack" (file-cat dir "help" "control" "pack.help.jmax"))
(help-patch "prepend" (file-cat dir "help" "control" "prepend.help.jmax"))
(help-patch "unpack" (file-cat dir "help" "control" "unpack.help.jmax"))

;; timing (9)
(help-patch "at" (file-cat dir "help" "control" "at.help.jmax"))
(help-patch "clock" (file-cat dir "help" "control" "clock.help.jmax"))
(help-patch "delay" (file-cat dir "help" "control" "delay.help.jmax"))
(help-patch "metro" (file-cat dir "help" "control" "metro.help.jmax"))
(help-patch "pipe" (file-cat dir "help" "control" "pipe.help.jmax"))
(help-patch "speedlim" (file-cat dir "help" "control" "speedlim.help.jmax"))
(help-patch "time" (file-cat dir "help" "control" "time.help.jmax"))
(help-patch "timer" (file-cat dir "help" "control" "timer.help.jmax"))

;; flow control (11)
(help-patch "bangbang" (file-cat dir "help" "control" "bangbang.help.jmax"))
(help-patch "change" (file-cat dir "help" "control" "change.help.jmax"))
(help-patch "gate" (file-cat dir "help" "control" "gate.help.jmax"))
(help-patch "loadbang" (file-cat dir "help" "control" "loadbang.help.jmax"))
(help-patch "route" (file-cat dir "help" "control" "route.help.jmax"))
(help-patch "select" (file-cat dir "help" "control" "select.help.jmax"))
(help-patch "split" (file-cat dir "help" "control" "split.help.jmax"))
(help-patch "swap" (file-cat dir "help" "control" "swap.help.jmax"))
(help-patch "trigger" (file-cat dir "help" "control" "trigger.help.jmax"))
;alias
(help-patch "t" (file-cat dir "help" "control" "trigger.help.jmax"))

;; genarators (6)
(help-patch "bpe" (file-cat dir "help" "control" "bpe.help.jmax"))
(help-patch "line" (file-cat dir "help" "control" "line.help.jmax"))
(help-patch "drunk" (file-cat dir "help" "control" "drunk.help.jmax"))
(help-patch "random" (file-cat dir "help" "control" "random.help.jmax"))

;; midi support (19)
(help-patch "Rsend" (file-cat dir "help" "control" "Rsend.help.jmax"))
(help-patch "Rreceive" (file-cat dir "help" "control" "Rsend.help.jmax"))
(help-patch "bendin" (file-cat dir "help" "control" "bendin.help.jmax"))
(help-patch "bendout" (file-cat dir "help" "control" "bendout.help.jmax"))
(help-patch "ctlin" (file-cat dir "help" "control" "ctlin.help.jmax"))
(help-patch "ctlout" (file-cat dir "help" "control" "ctlout.help.jmax"))
(help-patch "makenote" (file-cat dir "help" "control" "makenote.help.jmax"))
(help-patch "midiformat" (file-cat dir "help" "control" "midiformat.help.jmax"))
(help-patch "midiin" (file-cat dir "help" "control" "midiin.help.jmax"))
(help-patch "midiout" (file-cat dir "help" "control" "midiout.help.jmax"))
(help-patch "midiparse" (file-cat dir "help" "control" "midiparse.help.jmax"))
(help-patch "notein" (file-cat dir "help" "control" "notein.help.jmax"))
(help-patch "noteout" (file-cat dir "help" "control" "noteout.help.jmax"))
(help-patch "pgmin" (file-cat dir "help" "control" "pgmin.help.jmax"))
(help-patch "pgmout" (file-cat dir "help" "control" "pgmout.help.jmax"))
(help-patch "stripnote" (file-cat dir "help" "control" "stripnote.help.jmax"))
(help-patch "sysexin" (file-cat dir "help" "control" "sysexin.help.jmax"))
(help-patch "touchin" (file-cat dir "help" "control" "touchin.help.jmax"))
(help-patch "touchout" (file-cat dir "help" "control" "touchout.help.jmax"))

; polyphonic (2)
(help-patch "poly" (file-cat dir "help" "control" "poly.help.jmax"))
(help-patch "voxalloc" (file-cat dir "help" "control" "voxalloc.help.jmax"))

;; print (1)
(help-patch "print" (file-cat dir "help" "control" "print.help.jmax"))

;; Summary
(help-summary "ISPW control" (file-cat dir "help" "control" "ispw.control.summary.jmax"))
