;;
;; help declarations for the ispw control classes
;;

;; Summary
(help-summary "ISPW control summary" (file-cat dir "ispw.control.summary.jmax"))

;; misc math (10)
(help-patch "abs" (file-cat dir "abs.help.jmax"))
(help-patch "accum" (file-cat dir "accum.help.jmax"))
(help-patch "clip" (file-cat dir "clip.help.jmax"))
(help-patch "expr" (file-cat dir "expr.help.jmax"))
(help-patch "exscale" (file-cat dir "exscale.help.jmax"))
(help-patch "ftom" (file-cat dir "ftom.help.jmax"))
(help-patch "linedrive" (file-cat dir "linedrive.help.jmax"))
(help-patch "logscale" (file-cat dir "exscale.help.jmax"))
(help-patch "mtof" (file-cat dir "mtof.help.jmax"))
(help-patch "scale" (file-cat dir "scale.help.jmax"))

;; data (7)
(help-patch "bag" (file-cat dir "bag.help.jmax"))
(help-patch "float" (file-cat dir "float.help.jmax"))
(help-patch "funbuff" (file-cat dir "funbuff.help.jmax"))
(help-patch "int" (file-cat dir "int.help.jmax"))
(help-patch "pbank" (file-cat dir "pbank.help.jmax"))
(help-patch "table" (file-cat dir "table.help.jmax"))
(help-patch "value" (file-cat dir "value.help.jmax"))

;; lists (3)
(help-patch "pack" (file-cat dir "pack.help.jmax"))
(help-patch "prepend" (file-cat dir "prepend.help.jmax"))
(help-patch "unpack" (file-cat dir "unpack.help.jmax"))

;; timing (9)
(help-patch "at" (file-cat dir "at.help.jmax"))
(help-patch "clock" (file-cat dir "clock.help.jmax"))
(help-patch "delay" (file-cat dir "delay.help.jmax"))
(help-patch "metro" (file-cat dir "metro.help.jmax"))
(help-patch "pipe" (file-cat dir "pipe.help.jmax"))
(help-patch "speedlim" (file-cat dir "speedlim.help.jmax"))
(help-patch "time" (file-cat dir "time.help.jmax"))
(help-patch "timer" (file-cat dir "timer.help.jmax"))

;; flow control (11)
(help-patch "bangbang" (file-cat dir "bangbang.help.jmax"))
(help-patch "change" (file-cat dir "change.help.jmax"))
(help-patch "gate" (file-cat dir "gate.help.jmax"))
(help-patch "loadbang" (file-cat dir "loadbang.help.jmax"))
(help-patch "route" (file-cat dir "route.help.jmax"))
(help-patch "select" (file-cat dir "select.help.jmax"))
(help-patch "split" (file-cat dir "split.help.jmax"))
(help-patch "swap" (file-cat dir "swap.help.jmax"))
(help-patch "trigger" (file-cat dir "trigger.help.jmax"))
(help-patch "t" (file-cat dir "trigger.help.jmax"))

;; genarators (6)
(help-patch "bpe" (file-cat dir "bpe.help.jmax"))
(help-patch "line" (file-cat dir "line.help.jmax"))
(help-patch "drunk" (file-cat dir "drunk.help.jmax"))
(help-patch "random" (file-cat dir "random.help.jmax"))

;; midi support (19)
(help-patch "Rsend" (file-cat dir "Rsend.help.jmax"))
(help-patch "Rreceive" (file-cat dir "Rsend.help.jmax"))
(help-patch "bendin" (file-cat dir "bendin.help.jmax"))
(help-patch "bendout" (file-cat dir "bendout.help.jmax"))
(help-patch "ctlin" (file-cat dir "ctlin.help.jmax"))
(help-patch "ctlout" (file-cat dir "ctlout.help.jmax"))
(help-patch "makenote" (file-cat dir "makenote.help.jmax"))
(help-patch "midiformat" (file-cat dir "midiformat.help.jmax"))
(help-patch "midiin" (file-cat dir "midiin.help.jmax"))
(help-patch "midiout" (file-cat dir "midiout.help.jmax"))
(help-patch "midiparse" (file-cat dir "midiparse.help.jmax"))
(help-patch "notein" (file-cat dir "notein.help.jmax"))
(help-patch "noteout" (file-cat dir "noteout.help.jmax"))
(help-patch "pgmin" (file-cat dir "pgmin.help.jmax"))
(help-patch "pgmout" (file-cat dir "pgmout.help.jmax"))
(help-patch "stripnote" (file-cat dir "stripnote.help.jmax"))
(help-patch "sysexin" (file-cat dir "sysexin.help.jmax"))
(help-patch "touchin" (file-cat dir "touchin.help.jmax"))
(help-patch "touchout" (file-cat dir "touchout.help.jmax"))

; polyphonic (2)
(help-patch "poly" (file-cat dir "poly.help.jmax"))
(help-patch "voxalloc" (file-cat dir "voxalloc.help.jmax"))
