.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\".TH #UCPACKAGE# SECTION "#SHORTDATE#"
.TH jmax-config 1 "May 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jmax-config \- fts library configuration
.SH SYNOPSIS
.B jmax-config
.RI [ --package-dir ]
.RI [ --version ]
.RI [ --libs ]
.RI [ --cflags ]
.br
.B
.SH DESCRIPTION
This manual page documents briefly the
.B jmax-config
command. jmax-config can be used by autoconf scripts for building
jmax packages.
.PP
.SH OPTIONS
.\" These programs follow the usual GNU command line syntax, with long
.\"options starting with two dashes (`-').
A summary \fBjmax-config\fP of options is included below.
.\" For a complete description, see the Info files.
.TP
.B \-\-package\-dir
Returns the current jmax packages installation directory. Default is 
/usr/share/jmax/package.
.TP
.B \-\-version
Outputs \fBjmax\fP current version number.
.TP
.B \-\-libs
Outputs required flags for linking against fts shared library.
.TP
.B \-\-cflags
Outputs required flags for compiling against fts shared library.

.SH SEE ALSO
.BR jmax (1),
.BR fts (1),
.BR jmax2xml (1),
.br
Html documentation and examples are packaged in the jmax-doc 
debian package. See below for website. The programs are documented on
.IR "IRCAM website",
available at http://www.ircam.fr/jmax/.
.SH AUTHOR
This manual page was written by Paul Brossier <piem-lists _at_ altern_._org>,
for the Debian project (but may be used by others).
