.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\".TH #UCPACKAGE# SECTION "#SHORTDATE#"
.TH jmax 1 "May 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jmax \- Visual programming environment for audio and video
.SH SYNOPSIS
.B jmax
.RI [ -nofork ]
.RI [ -root | -r < directory >] 
.RI [ -verbose ]
.RI [ -javaopt < java-options >]
.br
.B fts 
.br
.SH DESCRIPTION
This manual page documents briefly the
.B jmax
and
.B fts
commands.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBjmax\fP is a visual programming environment for building interactive musical 
and multimedia applications. jMax is an implementation of the MAX software written
originally by Miller Puckette at Ircam. The name MAX is an homage to Max Matthews,
one of the fathers of computer music

\fBfts\fP (Faster Than Sound) is the signal and sound processing server for jmax. 
It is written in native C. For now, the only available client is a java gui. A
python interface is being developped (see debian package jmax-client).
.SH OPTIONS
.\" These programs follow the usual GNU command line syntax, with long
.\"options starting with two dashes (`-').
A summary \fBjmax\fP of options is included below.
.\" For a complete description, see the Info files.
.TP
.B \-nofork
Do not go into the background. By default, jMax forks itself to give control
back to the shell.
.TP
.B \-r, \-root <directory>
Specify the root directory (where to find the jmax.jar file, the initialization
scripts, etc.) Defaults to /usr/share/jmax.
.TP
.B \-javaopt <java-option>
Defines an option that is to be passed directly to the Java interpreter.
Several \fIjava-option\fP can appear in the command line, in which
case they will be concatenated.

Example: \fB-javaopt\fB \fI-verbose:gc\fP
.TP
.B -attach [true|false]
If \fItrue\fP, will not launch fts and will try to connect to the fts
server (see below \fB-jmaxConnection\fP). Default is \fIfalse\fP 
.TP
.B -host <hostname>
Defines fts server hostname.
.TP
.B -jmaxConnection [socket|pipe]
Ask jmax to connect fts through a TCP/IP \fIsocket\fP connection 
or a \fIpipe\fP  (default) connection.
.TP
.B <other-jmax-options> 
Defines jMax options that are passed directly to ircam.jmax.JMaxApplication as
command line options (for instance, \fIjmaxArch\fP, \fIjmaxMode\fP, ...).
.TP
.B \-help
Show summary of options.
.SH BUGS

By default, jmax tries to connect through pipe. This does not seem
to work. To launch, jmax, run \fIfts\fP on one side, then :
jmax -nofork -host localhost -attach true -jmaxConnection socket

.SH NOTES

jMax is started in background (i.e. the script terminates immediately). 
To override this, use \fI-nofork\fP option

The Java interpreter (started by the command \fIjava\fP) must be in the PATH.
.SH SEE ALSO
.BR fts (1),
.BR jmax2xml (1),
.BR jmax-config (1)
.br
Html documentation and examples are packaged in the jmax-doc 
debian package. See below for website. The programs are documented on
.IR "IRCAM website",
available at http://www.ircam.fr/jmax/.
.SH AUTHOR
This manual page was written by Paul Brossier <piem-lists_at_altern_._org>,
for the Debian project (but may be used by others).
