.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.\".TH #UCPACKAGE# SECTION "#SHORTDATE#"
.TH jmax2xml 1 "May 2003"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
jmax \- Visual programming environment for audio and video
.SH SYNOPSIS
.B jmax2xml
.RI < input.jmax >
.RI [ output.xml ]
.br
.B
.SH DESCRIPTION
This manual page documents briefly the
.B jmax2xml
command. jmax2xml can be used to convert jmax patches into XML.
If only \fBinput.jmax\fP is specified, outputs to std out. Otherwise,
outputs to \fIoutput.xml\fP.
.SH SEE ALSO
.BR jmax (1),
.BR fts (1),
.BR jmax-config (1),
.br
Html documentation and examples are packaged in the jmax-doc 
debian package. See below for website. The programs are documented on
.IR "IRCAM website",
available at http://www.ircam.fr/jmax/.
.SH AUTHOR
This manual page was written by Paul Brossier <piem-lists _at_ altern_._org>,
for the Debian project (but may be used by others).
