#!/bin/sh

# This script builds a SGI package.
#
# The optional argument is the directory where the package is build
#

BUILD_DIR=/data/jmax-build/src
if [ $# -ge 1 ]
then
    BUILD_DIR=$1
fi

# The root directory of sources
ROOT_DIR=../..

# Guess architecture
case `uname -m` in
IP27) ARCH=r10k-irix6.5 ;;
IP32) ARCH=r5k-irix6.5 ;;
esac

set -x

/bin/rm -rf $BUILD_DIR
mkdir -p $BUILD_DIR

VERSION=`cat $ROOT_DIR/VERSION`
DISTFILE=$ROOT_DIR/../jmax-$VERSION-src.tar.gz
SRCROOTDIR=jmax-$VERSION

gzip -cd $DISTFILE | (cd $BUILD_DIR ; tar xvf -)

( cd $BUILD_DIR/jmax-$VERSION ; gmake ARCH=$ARCH all)

/bin/rm -rf /tmp/jmax.idb /tmp/jmax.idb.sorted /tmp/jmax-sgi.spec

cp jmax-sgi.spec /tmp

(
    cd $BUILD_DIR/jmax-$VERSION

    RAWIDB=/tmp/jmax.idb
    export RAWIDB
    gmake ARCH=$ARCH INSTALL="install -idb ALL" install

    sort +4u -6 < /tmp/jmax.idb | awk '{ printf( "%s %s %s %s %c%s%c %c%s%c %s\n", $1, $2, $3, $4, 39, $5, 39, 39, $6, 39, $7); }' > /tmp/jmax.idb.sorted

    /usr/sbin/gendist -root .. -sbase .. -dist .. -idb /tmp/jmax.idb.sorted -spec /tmp/jmax-sgi.spec
)

( cd $BUILD_DIR ; tar cvf - jmax jmax.idb jmax.sw ) > $ROOT_DIR/../jmax-$VERSION.r10k.tardist 
/bin/rm -rf $BUILD_DIR


