/*
 * jMax
 * 
 * Copyright (C) 1999 by IRCAM
 * All rights reserved.
 * 
 * This program may be used and distributed under the terms of the 
 * accompanying LICENSE.
 *
 * This program is distributed WITHOUT ANY WARRANTY. See the LICENSE
 * for DISCLAIMER OF WARRANTY.
 * 
 */
/* DO NOT EDIT THIS FILE: it is generated automatically by the script jmax-make-new-version'' */

#define FTS_VERSION_STRING "jMax version 2.3.15\n"

