(define max-application-get-fts (method "getFts" "ircam.jmax.MaxApplication"))
(define max-application-set-fts (method "setFts" "ircam.jmax.MaxApplication" "ircam.jmax.fts.Fts"))
(define max-application-get-property (method "getProperty" "ircam.jmax.MaxApplication" "java.lang.String"))
(define max-application-set-property (method "setProperty" "ircam.jmax.MaxApplication" "java.lang.String" "java.lang.String"))
(define max-application-add-hook (method "addHook" "ircam.jmax.MaxApplication" "java.lang.String" "ircam.jmax.script.Script"))
(define max-application-run-hooks (method "runHooks" "ircam.jmax.MaxApplication" "java.lang.String"))
(define max-application-quit (method "Quit" "ircam.jmax.MaxApplication"))
(define max-application-install-editor-factory (method "installEditorFactory" "ircam.jmax.MaxApplication" "ircam.jmax.mda.MaxDataEditorFactory"))
(define max-application-install-document-handler (method "installDocumentHandler" "ircam.jmax.MaxApplication" "ircam.jmax.mda.MaxDocumentHandler"))
(define max-application-install-document-type (method "installDocumentType" "ircam.jmax.MaxApplication" "ircam.jmax.mda.MaxDocumentType"))
(define interpreter-convert (method "convert" "ircam.jmax.script.Interpreter" "java.lang.Object"))
(define interpreter-get-package-handler (method "getPackageHandler" "ircam.jmax.script.Interpreter"))
(define interpreter-load-package (method "loadPackage" "ircam.jmax.script.Interpreter" "ircam.jmax.script.pkg.Package" "java.io.File"))
(define interpreter-load-project (method "loadProject" "ircam.jmax.script.Interpreter" "ircam.jmax.script.pkg.Package" "java.io.File"))
(define interpreter-load-scripted-document (method "loadScriptedDocument" "ircam.jmax.script.Interpreter" "ircam.jmax.script.pkg.Package" "java.io.File"))
(define interpreter-add-script-menu-item (method "addScriptMenuItem" "ircam.jmax.script.Interpreter" "java.lang.String" "java.lang.String" "java.lang.Object" "ircam.jmax.script.Script"))
(define scheme-interpreter-get-key-stroke (method "getKeyStroke" "ircam.jmax.script.scm.SchemeInterpreter" "java.lang.String" "boolean" "boolean" "boolean" "boolean"))
(define scheme-interpreter-load-silently (method "loadSilently" "ircam.jmax.script.scm.SchemeInterpreter" "java.lang.String"))
(define scheme-interpreter-to-java-string (method "toJavaString" "ircam.jmax.script.scm.SchemeInterpreter" "java.lang.Object"))
(define scheme-interpreter-is-null (method "isNull" "ircam.jmax.script.scm.SchemeInterpreter" "java.lang.Object"))
(define package-handler-set-unknown-script (method "setUnknownScript" "ircam.jmax.script.pkg.PackageHandler" "ircam.jmax.script.Script"))
(define package-handler-get-unknown-script (method "getUnknownScript" "ircam.jmax.script.pkg.PackageHandler"))
(define package-handler-provide (method "provide" "ircam.jmax.script.pkg.PackageHandler" "java.lang.String" "java.lang.String"))
(define package-handler-forget (method "forget" "ircam.jmax.script.pkg.PackageHandler" "java.lang.String"))
(define package-handler-require (method "require" "ircam.jmax.script.pkg.PackageHandler" "java.lang.String" "java.lang.String"))
(define package-handler-append-path (method "appendPath" "ircam.jmax.script.pkg.PackageHandler" "java.lang.String"))
(define package-load-class (method "loadClass" "ircam.jmax.script.pkg.Package" "java.lang.String"))
(define package-append-local-path (method "appendLocalPath" "ircam.jmax.script.pkg.Package" "java.lang.String"))
(define new-fts (constructor "ircam.jmax.fts.Fts" "java.lang.String" "java.lang.String" "java.lang.String" "java.lang.String" "int"))
(define fts-make-fts-object (method "makeFtsObject" "ircam.jmax.fts.Fts" "ircam.jmax.fts.FtsObject" "java.lang.String" "java.lang.String"))
(define fts-make-fts-connection (method "makeFtsConnection" "ircam.jmax.fts.Fts" "ircam.jmax.fts.FtsObject" "int" "ircam.jmax.fts.FtsObject" "int"))
(define fts-redefine-fts-object (method "redefineFtsObject" "ircam.jmax.fts.Fts" "ircam.jmax.fts.FtsObject" "java.lang.String"))
(define fts-get-selection (method "getSelection" "ircam.jmax.fts.Fts"))
(define fts-sync (method "sync" "ircam.jmax.fts.Fts"))
(define fts-stop (method "stop" "ircam.jmax.fts.Fts"))
(define fts-abstraction-declare (method "abstractionDeclare" "ircam.jmax.fts.Fts" "java.lang.String" "java.lang.String"))
(define fts-abstraction-path-declare (method "abstractionPathDeclare" "ircam.jmax.fts.Fts" "java.lang.String"))
(define fts-template-declare (method "templateDeclare" "ircam.jmax.fts.Fts" "java.lang.String" "java.lang.String"))
(define fts-template-path-declare (method "templatePathDeclare" "ircam.jmax.fts.Fts" "java.lang.String"))
(define fts-ucs-command (method "ucsCommand" "ircam.jmax.fts.Fts" "ircam.jmax.utils.MaxVector"))
(define fts-help-patch-table-add (method "add" "ircam.jmax.fts.FtsHelpPatchTable" "java.lang.String" "java.lang.String"))
(define fts-help-patch-table-add-summary (method "addSummary" "ircam.jmax.fts.FtsHelpPatchTable" "java.lang.String" "java.lang.String"))
(define fts-reference-u-r-l-table-add (method "add" "ircam.jmax.fts.FtsReferenceURLTable" "java.lang.String" "java.lang.String"))
(define mda-install-editor-factory (method "installEditorFactory" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxDataEditorFactory"))
(define mda-edit (method "edit" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxData"))
(define mda-install-document-handler (method "installDocumentHandler" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxDocumentHandler"))
(define mda-can-load-document (method "canLoadDocument" "ircam.jmax.mda.Mda" "java.io.File"))
(define mda-load-document (method "loadDocument" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxContext" "java.io.File"))
(define mda-find-document-handler-for (method "findDocumentHandlerFor" "ircam.jmax.mda.Mda" "java.io.File" "ircam.jmax.mda.MaxDocument"))
(define mda-install-document-type (method "installDocumentType" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxDocumentType"))
(define mda-new-document (method "newDocument" "ircam.jmax.mda.Mda" "ircam.jmax.mda.MaxData"))
(define max-document-get-name (method "getName" "ircam.jmax.mda.MaxDocument"))
(define max-document-set-name (method "setName" "ircam.jmax.mda.MaxDocument" "java.lang.String"))
(define max-document-edit (method "edit" "ircam.jmax.mda.MaxDocument"))
(define max-document-save (method "save" "ircam.jmax.mda.MaxDocument"))
(define max-document-save-to (method "saveTo" "ircam.jmax.mda.MaxDocument" "java.io.File"))
(define max-document-dispose (method "dispose" "ircam.jmax.mda.MaxDocument"))
(define icons-load-icon (method "loadIcon" "ircam.jmax.toolkit.Icons" "java.lang.String" "java.lang.String"))
(define new-max-vector (constructor "ircam.jmax.utils.MaxVector"))
(define max-vector-add-element (method "addElement" "ircam.jmax.utils.MaxVector" "java.lang.Object"))
(define add-pop-up-add-abbreviation (method "addAbbreviation" "ircam.jmax.editors.patcher.AddPopUp" "java.lang.String" "java.lang.String" "java.lang.String" "boolean"))
(define add-pop-up-add-abbreviation1 (method "addAbbreviation" "ircam.jmax.editors.patcher.AddPopUp" "java.lang.String" "java.lang.String" "java.lang.String" "java.lang.String" "boolean"))
(define new-console-window (constructor "ircam.jmax.editors.console.ConsoleWindow"))
(define new-splash-dialog (constructor "ircam.jmax.dialogs.SplashDialog" "java.lang.String" "java.lang.String"))
(define system-current-time-millis (method "currentTimeMillis" "java.lang.System"))
(define system-get-properties (method "getProperties" "java.lang.System"))
(define object-get-class (method "getClass" "java.lang.Object"))
(define object-to-string (method "toString" "java.lang.Object"))
(define new-string2 (constructor "java.lang.String" "[C"))
(define string-length (method "length" "java.lang.String"))
(define number-int-value (method "intValue" "java.lang.Number"))
(define number-float-value (method "floatValue" "java.lang.Number"))
(define new-float (constructor "java.lang.Float" "float"))
(define new-integer (constructor "java.lang.Integer" "int"))
(define class-for-name (method "forName" "java.lang.Class" "java.lang.String"))
(define new-file (constructor "java.io.File" "java.lang.String"))
(define file-exists (method "exists" "java.io.File"))
(define hashtable-get (method "get" "java.util.Hashtable" "java.lang.Object"))
(define hashtable-put (method "put" "java.util.Hashtable" "java.lang.Object" "java.lang.Object"))
